services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Aistea\AisCareer\:
    resource: '../Classes/*'

  Aistea\AisCareer\Controller\JobController:
    public: true
    tags: ['controller.service_arguments']

  Aistea\AisCareer\Command\PurgeApplicationsCommand:
    tags:
      - name: 'console.command'
        command: 'aiscareer:purge-applications'
